/**
 * Tests for the stream relay: ffmpeg argument builder, RTMP URL redaction,
 * ffmpeg progress line parsing, and an end-to-end pipe test that feeds real
 * fragmented MP4 (generated by ffmpeg, same container the extension
 * MediaRecorder produces) through StreamRelay into an flv output file.
 */
import { spawn, spawnSync } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { describe, test, expect } from 'vitest'
import { StreamRelay, buildStreamFfmpegArgs, redactStreamUrl, escapeTeeUrl, parseFfmpegProgressLine } from './stream-relay.js'
import { probeVideo } from './ffmpeg.js'
import type { StopRecordingParams } from './protocol.js'

const hasFfmpeg = spawnSync('ffmpeg', ['-version'], { stdio: 'ignore' }).status === 0

describe('buildStreamFfmpegArgs', () => {
  test('single destination with libx264 and tab audio', () => {
    const args = buildStreamFfmpegArgs({
      rtmpUrls: ['rtmp://va.pscp.tv:80/x/streamkey'],
      width: 1280,
      height: 720,
      fps: 30,
      videoBitrateKbps: 4500,
      audioBitrateKbps: 128,
      audio: true,
      preset: 'veryfast',
      codec: 'libx264',
      keyframeSeconds: 3,
    })
    expect(args.join(' ')).toMatchInlineSnapshot(`"-hide_banner -nostdin -i pipe:0 -map 0:v:0 -map 0:a:0 -vf scale=1280:720 -r 30 -c:v libx264 -b:v 4500k -maxrate 4500k -bufsize 9000k -pix_fmt yuv420p -g 90 -keyint_min 90 -preset veryfast -tune zerolatency -sc_threshold 0 -c:a aac -b:a 128k -ar 44100 -ac 2 -f flv rtmp://va.pscp.tv:80/x/streamkey"`)
  })

  test('multi destination uses tee muxer with onfail=ignore', () => {
    const args = buildStreamFfmpegArgs({
      rtmpUrls: ['rtmp://live.twitch.tv/app/key1', 'rtmp://va.pscp.tv:80/x/key2'],
      width: 1920,
      height: 1080,
      fps: 60,
      videoBitrateKbps: 6000,
      audioBitrateKbps: 160,
      audio: true,
      preset: 'fast',
      codec: 'libx264',
      keyframeSeconds: 2,
    })
    expect(args.join(' ')).toMatchInlineSnapshot(`"-hide_banner -nostdin -i pipe:0 -map 0:v:0 -map 0:a:0 -vf scale=1920:1080 -r 60 -c:v libx264 -b:v 6000k -maxrate 6000k -bufsize 12000k -pix_fmt yuv420p -g 120 -keyint_min 120 -preset fast -tune zerolatency -sc_threshold 0 -c:a aac -b:a 160k -ar 44100 -ac 2 -flags +global_header -f tee -use_fifo 1 -fifo_options attempt_recovery=1:recover_any_error=1 [f=flv:onfail=ignore]rtmp://live.twitch.tv/app/key1|[f=flv:onfail=ignore]rtmp://va.pscp.tv:80/x/key2"`)
  })

  test('no audio injects silent anullsrc track', () => {
    const args = buildStreamFfmpegArgs({
      rtmpUrls: ['rtmp://a.rtmp.youtube.com/live2/key'],
      width: 1280,
      height: 720,
      fps: 30,
      videoBitrateKbps: 4500,
      audioBitrateKbps: 128,
      audio: false,
      preset: 'veryfast',
      codec: 'libx264',
      keyframeSeconds: 3,
    })
    expect(args.join(' ')).toMatchInlineSnapshot(`"-hide_banner -nostdin -i pipe:0 -f lavfi -i anullsrc=r=44100:cl=stereo -map 0:v:0 -map 1:a:0 -shortest -vf scale=1280:720 -r 30 -c:v libx264 -b:v 4500k -maxrate 4500k -bufsize 9000k -pix_fmt yuv420p -g 90 -keyint_min 90 -preset veryfast -tune zerolatency -sc_threshold 0 -c:a aac -b:a 128k -ar 44100 -ac 2 -f flv rtmp://a.rtmp.youtube.com/live2/key"`)
  })

  test('hardware encoder skips x264-only flags', () => {
    const args = buildStreamFfmpegArgs({
      rtmpUrls: ['rtmp://host/app/key'],
      width: 1280,
      height: 720,
      fps: 30,
      videoBitrateKbps: 4500,
      audioBitrateKbps: 128,
      audio: true,
      preset: 'veryfast',
      codec: 'h264_videotoolbox',
      keyframeSeconds: 3,
    })
    expect(args.join(' ')).toMatchInlineSnapshot(`"-hide_banner -nostdin -i pipe:0 -map 0:v:0 -map 0:a:0 -vf scale=1280:720 -r 30 -c:v h264_videotoolbox -b:v 4500k -maxrate 4500k -bufsize 9000k -pix_fmt yuv420p -g 90 -keyint_min 90 -realtime true -c:a aac -b:a 128k -ar 44100 -ac 2 -f flv rtmp://host/app/key"`)
  })

  test('throws without destinations', () => {
    expect(() => {
      buildStreamFfmpegArgs({
        rtmpUrls: [],
        width: 1280,
        height: 720,
        fps: 30,
        videoBitrateKbps: 4500,
        audioBitrateKbps: 128,
        audio: true,
        preset: 'veryfast',
        codec: 'libx264',
        keyframeSeconds: 3,
      })
    }).toThrowErrorMatchingInlineSnapshot(`[Error: At least one RTMP destination is required]`)
  })
})

describe('escapeTeeUrl', () => {
  test('escapes tee-special characters', () => {
    expect(escapeTeeUrl('rtmp://host/app/key|with[brackets]')).toMatchInlineSnapshot(`"rtmp://host/app/key\\|with\\[brackets\\]"`)
    expect(escapeTeeUrl('rtmp://host/app/plainkey')).toMatchInlineSnapshot(`"rtmp://host/app/plainkey"`)
  })
})

describe('redactStreamUrl', () => {
  test('redacts stream keys but keeps host', () => {
    expect(redactStreamUrl('rtmp://live.twitch.tv/app/live_123456_SECRET')).toMatchInlineSnapshot(`"rtmp://live.twitch.tv/…"`)
    expect(redactStreamUrl('rtmps://va.pscp.tv:443/x/SECRETKEY')).toMatchInlineSnapshot(`"rtmps://va.pscp.tv:443/…"`)
    // file paths (used in tests) pass through
    expect(redactStreamUrl('/tmp/out.flv')).toMatchInlineSnapshot(`"/tmp/out.flv"`)
  })
})

describe('parseFfmpegProgressLine', () => {
  test('parses progress stats', () => {
    expect(
      parseFfmpegProgressLine(
        'frame=  123 fps= 30 q=28.0 size=    1024KiB time=00:00:04.10 bitrate=2045.6kbits/s drop=2 speed=1.01x',
      ),
    ).toMatchInlineSnapshot(`
      {
        "bitrateKbps": 2045.6,
        "droppedFrames": 2,
        "fps": 30,
      }
    `)
  })

  test('returns null for non-progress lines', () => {
    expect(parseFfmpegProgressLine('[flv @ 0x7f8] Failed to update header')).toMatchInlineSnapshot(`null`)
  })
})

/** Generate a short fragmented MP4 (H.264 + AAC) in memory - the same
 *  streamable container the extension MediaRecorder emits. */
function generateFragmentedMp4(): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const child = spawn('ffmpeg', [
      '-hide_banner', '-loglevel', 'error',
      '-f', 'lavfi', '-i', 'testsrc=size=320x240:rate=30:duration=2',
      '-f', 'lavfi', '-i', 'sine=frequency=440:duration=2',
      '-c:v', 'libx264', '-preset', 'ultrafast',
      '-c:a', 'aac',
      '-f', 'mp4', '-movflags', 'frag_keyframe+empty_moov+default_base_moof',
      'pipe:1',
    ])
    const chunks: Buffer[] = []
    child.stdout.on('data', (data: Buffer) => {
      chunks.push(data)
    })
    child.on('close', (code) => {
      if (code === 0) {
        resolve(Buffer.concat(chunks))
      } else {
        reject(new Error(`ffmpeg testsrc generation failed with code ${code}`))
      }
    })
    child.on('error', reject)
  })
}

describe.skipIf(!hasFfmpeg)('StreamRelay end-to-end pipe', () => {
  test('pipes fMP4 chunks through ffmpeg to an flv destination', async () => {
    const tabId = 42
    const outputPath = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'pw-stream-test-')), 'out.flv')

    // Dependency-injected extension transport: startRecording succeeds
    // immediately; stopRecording triggers the final recordingData message
    // asynchronously, exactly like the real extension does over WS.
    const relayRef: { current: StreamRelay | null } = { current: null }
    const sentMethods: string[] = []
    const sendToExtension = async ({ method }: { method: string; params?: unknown; timeout?: number }) => {
      sentMethods.push(method)
      if (method === 'startRecording') {
        return { success: true, tabId, startedAt: Date.now() }
      }
      if (method === 'stopRecording') {
        queueMicrotask(() => {
          relayRef.current?.handleRecordingData({ method: 'recordingData', params: { tabId, final: true } })
        })
        return { success: true, tabId, duration: 2000 }
      }
      return { success: true }
    }
    const relay = new StreamRelay(sendToExtension, () => true)
    relayRef.current = relay

    const startResult = await relay.startStream({
      rtmpUrls: [outputPath],
      resolution: '320x240',
      fps: 30,
      videoBitrateKbps: 500,
      audioBitrateKbps: 64,
      audio: true,
      codec: 'libx264',
    })
    expect(startResult).toMatchObject({ success: true, tabId })

    const status = relay.streamStatus({})
    expect(status.streaming).toBe(true)
    expect(status.destinations).toEqual([outputPath])

    // Feed the capture in 64KB chunks, each preceded by its metadata message
    // like the extension does (recordingData without final, then binary).
    const mp4 = await generateFragmentedMp4()
    expect(mp4.length).toBeGreaterThan(10000)
    const chunkSize = 64 * 1024
    for (let offset = 0; offset < mp4.length; offset += chunkSize) {
      relay.handleRecordingData({ method: 'recordingData', params: { tabId } })
      const consumed = relay.handleBinaryData(mp4.subarray(offset, offset + chunkSize))
      expect(consumed).toBe(true)
    }

    const stopResult = await relay.stopStream({})
    expect(stopResult.success).toBe(true)
    if (stopResult.success) {
      expect(stopResult.bytesReceived).toBe(mp4.length)
    }
    expect(sentMethods).toEqual(['startRecording', 'stopRecording'])
    expect(relay.streamStatus({}).streaming).toBe(false)

    // The flv output must be a valid re-encoded video
    const info = await probeVideo(outputPath)
    expect(info).toMatchObject({ width: 320, height: 240 })

    fs.rmSync(path.dirname(outputPath), { recursive: true, force: true })
  }, 30000)

  test('concurrent stopStream calls share one result', async () => {
    const tabId = 43
    const outputPath = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'pw-stream-test-')), 'out.flv')
    const relayRef: { current: StreamRelay | null } = { current: null }
    const sendToExtension = async ({ method }: { method: string; params?: unknown; timeout?: number }) => {
      if (method === 'startRecording') {
        return { success: true, tabId, startedAt: Date.now() }
      }
      if (method === 'stopRecording') {
        queueMicrotask(() => {
          relayRef.current?.handleRecordingData({ method: 'recordingData', params: { tabId, final: true } })
        })
        return { success: true, tabId, duration: 100 }
      }
      return { success: true }
    }
    const relay = new StreamRelay(sendToExtension, () => true)
    relayRef.current = relay

    await relay.startStream({ rtmpUrls: [outputPath], resolution: '320x240', audio: false, codec: 'libx264' })
    const mp4 = await generateFragmentedMp4()
    relay.handleRecordingData({ method: 'recordingData', params: { tabId } })
    relay.handleBinaryData(mp4)

    // Both concurrent stops must settle with the same result (regression:
    // the second call used to overwrite resolveStop, orphaning the first).
    const [first, second] = await Promise.all([relay.stopStream({}), relay.stopStream({})])
    expect(first).toEqual(second)
    expect(first.success).toBe(true)

    fs.rmSync(path.dirname(outputPath), { recursive: true, force: true })
  }, 30000)

  test('extension stopRecording failure resolves stop with error, not false success', async () => {
    const tabId = 44
    const outputPath = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'pw-stream-test-')), 'out.flv')
    const sendToExtension = async ({ method }: { method: string; params?: unknown; timeout?: number }) => {
      if (method === 'startRecording') {
        return { success: true, tabId, startedAt: Date.now() }
      }
      if (method === 'stopRecording') {
        // Extension reports operational failures without throwing
        return { success: false, error: 'Tab was closed' }
      }
      return { success: true }
    }
    const relay = new StreamRelay(sendToExtension, () => true)

    await relay.startStream({ rtmpUrls: [outputPath], resolution: '320x240', audio: false, codec: 'libx264' })
    const mp4 = await generateFragmentedMp4()
    relay.handleRecordingData({ method: 'recordingData', params: { tabId } })
    relay.handleBinaryData(mp4)

    const stopResult = await relay.stopStream({})
    expect(stopResult.success).toBe(false)
    if (!stopResult.success) {
      expect(stopResult.error).toContain('Tab was closed')
    }

    fs.rmSync(path.dirname(outputPath), { recursive: true, force: true })
  }, 30000)

  test('ffmpeg errors never expose the stream key', async () => {
    const tabId = 45
    // Unreachable RTMP endpoint: ffmpeg fails to connect and its stderr
    // echoes the full URL including the stream key
    const secretUrl = 'rtmp://127.0.0.1:1/live/SUPERSECRETKEY'
    const sendToExtension = async ({ method }: { method: string; params?: unknown; timeout?: number }) => {
      if (method === 'startRecording') {
        return { success: true, tabId, startedAt: Date.now() }
      }
      return { success: true }
    }
    const relay = new StreamRelay(sendToExtension, () => true)

    const startResult = await relay.startStream({
      rtmpUrls: [secretUrl],
      resolution: '320x240',
      audio: false,
      codec: 'libx264',
    })
    expect(startResult.success).toBe(true)
    if (startResult.success) {
      expect(startResult.destinations).toEqual(['rtmp://127.0.0.1:1/…'])
    }

    // Feed data so ffmpeg starts and hits the connection failure
    const mp4 = await generateFragmentedMp4()
    relay.handleRecordingData({ method: 'recordingData', params: { tabId } })
    relay.handleBinaryData(mp4)

    // Wait for ffmpeg to die from the failed connection
    await new Promise<void>((resolve, reject) => {
      const deadline = Date.now() + 15000
      const poll = () => {
        if (!relay.streamStatus({}).streaming) {
          resolve()
          return
        }
        if (Date.now() > deadline) {
          reject(new Error('ffmpeg did not exit within 15s'))
          return
        }
        setTimeout(poll, 100)
      }
      poll()
    })

    const status = relay.streamStatus({})
    expect(status.streaming).toBe(false)
    expect(status.error).toBeTruthy()
    expect(JSON.stringify(status)).not.toContain('SUPERSECRETKEY')
  }, 30000)

  test('unknown tab chunks are not consumed', async () => {
    const relay = new StreamRelay(async () => ({ success: true }), () => true)
    expect(relay.handleRecordingData({ method: 'recordingData', params: { tabId: 7 } })).toBe(false)
    expect(relay.handleBinaryData(Buffer.from('abc'))).toBe(false)
    const stopParams: StopRecordingParams = {}
    const stopResult = await relay.stopStream(stopParams)
    expect(stopResult).toMatchInlineSnapshot(`
      {
        "error": "No active stream found",
        "success": false,
      }
    `)
  })
})
